"""Payment type definitions.

Defines the normalised response shapes returned by every payment
provider.  All providers **must** return exactly these shapes so that
business modules never need to know which provider is active.

Money values use ``Decimal`` — never ``float``.

These shapes are **locked** and must not be modified without an
explicit architectural decision.
"""

from decimal import Decimal
from typing import Optional, TypedDict


class InitializationResponse(TypedDict):
    """Normalised response from a payment initialisation request.

    Attributes:
        provider: Identifier of the payment provider (e.g. ``"chapa"``).
        status: Normalised status string (e.g. ``"success"``, ``"pending"``).
        provider_status: Raw status string returned by the provider.
        reference: Unique transaction reference generated by the caller.
        provider_transaction_id: Provider-assigned transaction ID, or
            ``None`` if not available at initialisation time.
        amount: Payment amount as a ``Decimal``.
        currency: ISO 4217 currency code (e.g. ``"ETB"``).
        checkout_url: URL the end-user should be redirected to for payment.
        raw: Complete raw response payload from the provider for
            debugging and audit purposes.
    """

    provider: str
    status: str
    provider_status: str
    reference: str
    provider_transaction_id: Optional[str]
    amount: Decimal
    currency: str
    checkout_url: str
    raw: dict


class VerificationResponse(TypedDict):
    """Normalised response from a payment verification request.

    Attributes:
        provider: Identifier of the payment provider (e.g. ``"chapa"``).
        status: Normalised status string (e.g. ``"success"``, ``"failed"``).
        provider_status: Raw status string returned by the provider.
        reference: Transaction reference that was verified.
        provider_transaction_id: Provider-assigned transaction ID, or
            ``None`` if not returned.
        amount: Verified payment amount as a ``Decimal``, or ``None``
            if the provider does not return it.
        currency: ISO 4217 currency code (e.g. ``"ETB"``).
        raw: Complete raw response payload from the provider.
    """

    provider: str
    status: str
    provider_status: str
    reference: str
    provider_transaction_id: Optional[str]
    amount: Optional[Decimal]
    currency: str
    raw: dict
