# Generated by Django 5.2.15 on 2026-07-07 19:46

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0004_alter_user_options_alter_user_status'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Program',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, unique=True)),
                ('slug', models.SlugField(max_length=255, unique=True)),
                ('description', models.TextField(blank=True, default='')),
                ('supports_group', models.BooleanField(default=True)),
                ('supports_individual', models.BooleanField(default=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Program',
                'verbose_name_plural': 'Programs',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='SubProgram',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('slug', models.SlugField(max_length=255)),
                ('description', models.TextField(blank=True, default='')),
                ('duration', models.PositiveIntegerField(blank=True, null=True)),
                ('duration_unit', models.CharField(blank=True, choices=[('DAY', 'Day'), ('WEEK', 'Week'), ('MONTH', 'Month')], max_length=10, null=True)),
                ('fee', models.DecimalField(decimal_places=2, max_digits=10)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('program', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sub_programs', to='academic.program')),
            ],
            options={
                'verbose_name': 'Sub Program',
                'verbose_name_plural': 'Sub Programs',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Class',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('class_type', models.CharField(choices=[('GROUP', 'Group'), ('INDIVIDUAL', 'Individual')], max_length=10)),
                ('capacity', models.PositiveIntegerField(blank=True, null=True)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='classes', to='accounts.branch')),
                ('instructor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='classes', to=settings.AUTH_USER_MODEL)),
                ('sub_program', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='classes', to='academic.subprogram')),
            ],
            options={
                'verbose_name': 'Class',
                'verbose_name_plural': 'Classes',
                'ordering': ['name'],
            },
        ),
        migrations.AddConstraint(
            model_name='subprogram',
            constraint=models.UniqueConstraint(fields=('program', 'name'), name='unique_sub_program_per_program'),
        ),
        migrations.AddConstraint(
            model_name='subprogram',
            constraint=models.UniqueConstraint(fields=('program', 'slug'), name='unique_sub_program_slug_per_program'),
        ),
    ]
