# Generated by Django 5.2.15 on 2026-07-08 11:45

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academic', '0004_student_guardian_email_student_guardian_name_and_more'),
        ('accounts', '0005_alter_userassignment_role'),
    ]

    operations = [
        migrations.CreateModel(
            name='EnrollmentPeriod',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('class_type', models.CharField(choices=[('GROUP', 'Group'), ('INDIVIDUAL', 'Individual')], max_length=10)),
                ('title', models.CharField(max_length=255)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='enrollment_periods', to='accounts.branch')),
                ('program', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='enrollment_periods', to='academic.program')),
                ('sub_program', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='enrollment_periods', to='academic.subprogram')),
            ],
            options={
                'verbose_name': 'Enrollment Period',
                'verbose_name_plural': 'Enrollment Periods',
                'ordering': ['-start_date'],
            },
        ),
    ]
