# Generated by Django 5.2.15 on 2026-07-08 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academic', '0005_enrollment_period'),
    ]

    operations = [
        migrations.AddField(
            model_name='enrollmentperiod',
            name='class_period',
            field=models.CharField(blank=True, choices=[('GROUP', 'Group'), ('INDIVIDUAL', 'Individual')], max_length=10, null=True),
        ),
    ]
