# Generated by Django 5.2.15 on 2026-07-08 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academic', '0006_enrollmentperiod_class_period'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enrollmentperiod',
            name='class_period',
            field=models.CharField(blank=True, choices=[('FULL_DAY', 'Full Day'), ('HALF_DAY', 'Half Day')], max_length=10, null=True),
        ),
    ]
