# Generated by Django 5.2.15 on 2026-07-08 15:32

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academic', '0010_attendancesession_attendancerecord_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LearningMilestone',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, default='')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('scope_class', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='milestones', to='academic.class')),
                ('sub_program', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='milestones', to='academic.subprogram')),
            ],
            options={
                'verbose_name': 'Learning Milestone',
                'verbose_name_plural': 'Learning Milestones',
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='StudentProgress',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('NOT_STARTED', 'Not Started'), ('IN_PROGRESS', 'In Progress'), ('COMPLETED', 'Completed')], default='NOT_STARTED', max_length=20)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('remarks', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('enrollment', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='progress_records', to='academic.enrollment')),
                ('milestone', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='student_progress', to='academic.learningmilestone')),
                ('updated_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='progress_updates', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Student Progress',
                'verbose_name_plural': 'Student Progress Records',
                'ordering': ['milestone__title'],
            },
        ),
        migrations.AddConstraint(
            model_name='learningmilestone',
            constraint=models.UniqueConstraint(fields=('sub_program', 'scope_class', 'title'), name='unique_milestone_per_scope'),
        ),
        migrations.AddConstraint(
            model_name='studentprogress',
            constraint=models.UniqueConstraint(fields=('enrollment', 'milestone'), name='unique_progress_per_enrollment_milestone'),
        ),
    ]
