# Generated by Django 5.2.15 on 2026-07-08 15:51

import apps.academic.models.learning_material
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academic', '0011_learningmilestone_studentprogress_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LearningMaterial',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, default='')),
                ('file', models.FileField(upload_to=apps.academic.models.learning_material.learning_material_upload_to)),
                ('material_type', models.CharField(choices=[('PDF', 'PDF'), ('PPT', 'PPT'), ('PPTX', 'PPTX'), ('DOC', 'DOC'), ('DOCX', 'DOCX'), ('IMAGE', 'Image'), ('OTHER', 'Other')], editable=False, max_length=10)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('sub_program', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='learning_materials', to='academic.subprogram')),
                ('uploaded_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='uploaded_materials', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Learning Material',
                'verbose_name_plural': 'Learning Materials',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['sub_program'], name='academic_le_sub_pro_518b89_idx'), models.Index(fields=['uploaded_by'], name='academic_le_uploade_69980e_idx'), models.Index(fields=['material_type'], name='academic_le_materia_ed8980_idx'), models.Index(fields=['is_active'], name='academic_le_is_acti_234017_idx')],
            },
        ),
    ]
