# Generated by Django 5.2.15 on 2026-07-08 16:48

import apps.academic.models.learning_material
import apps.shared.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academic', '0012_learningmaterial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='learningmaterial',
            name='file',
            field=models.FileField(upload_to=apps.academic.models.learning_material.learning_material_upload_to, validators=[apps.shared.validators.UploadedFileValidator()]),
        ),
        migrations.AlterField(
            model_name='learningmaterial',
            name='material_type',
            field=models.CharField(choices=[('PDF', 'PDF'), ('PPT', 'PPT'), ('PPTX', 'PPTX'), ('DOC', 'DOC'), ('DOCX', 'DOCX'), ('IMAGE', 'Image')], editable=False, max_length=10),
        ),
    ]
