# Generated by Django 5.2.15 on 2026-07-08 17:07

import apps.academic.models.certificate
import apps.shared.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academic', '0013_alter_materialtype_choices'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Certificate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('background', models.ImageField(upload_to=apps.academic.models.certificate.certificate_bg_upload_to, validators=[apps.shared.validators.UploadedFileValidator()])),
                ('institute_logo', models.ImageField(blank=True, null=True, upload_to=apps.academic.models.certificate.certificate_logo_upload_to, validators=[apps.shared.validators.UploadedFileValidator()])),
                ('signature', models.ImageField(blank=True, null=True, upload_to=apps.academic.models.certificate.certificate_sig_upload_to, validators=[apps.shared.validators.UploadedFileValidator()])),
                ('body_text', models.TextField()),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('sub_program', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='certificate', to='academic.subprogram')),
            ],
            options={
                'verbose_name': 'Certificate Template',
                'verbose_name_plural': 'Certificate Templates',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='StudentCertificate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('certificate_number', models.CharField(db_index=True, max_length=50, unique=True)),
                ('issued_at', models.DateTimeField(auto_now_add=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('certificate', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='issued', to='academic.certificate')),
                ('issued_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='issued_certificates', to=settings.AUTH_USER_MODEL)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='certificates', to='academic.student')),
                ('sub_program', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='student_certificates', to='academic.subprogram')),
            ],
            options={
                'verbose_name': 'Student Certificate',
                'verbose_name_plural': 'Student Certificates',
                'ordering': ['-issued_at'],
            },
        ),
        migrations.AddIndex(
            model_name='certificate',
            index=models.Index(fields=['sub_program'], name='academic_ce_sub_pro_629619_idx'),
        ),
        migrations.AddIndex(
            model_name='certificate',
            index=models.Index(fields=['is_active'], name='academic_ce_is_acti_5c00af_idx'),
        ),
        migrations.AddIndex(
            model_name='studentcertificate',
            index=models.Index(fields=['student'], name='academic_st_student_e4e453_idx'),
        ),
        migrations.AddIndex(
            model_name='studentcertificate',
            index=models.Index(fields=['certificate'], name='academic_st_certifi_b0772b_idx'),
        ),
        migrations.AddIndex(
            model_name='studentcertificate',
            index=models.Index(fields=['sub_program'], name='academic_st_sub_pro_ba2a03_idx'),
        ),
        migrations.AddIndex(
            model_name='studentcertificate',
            index=models.Index(fields=['certificate_number'], name='academic_st_certifi_89ca47_idx'),
        ),
        migrations.AddConstraint(
            model_name='studentcertificate',
            constraint=models.UniqueConstraint(fields=('student', 'sub_program'), name='unique_student_sub_program_cert'),
        ),
    ]
