# Generated by Django 5.2.15 on 2026-07-08 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academic', '0014_certificate_models'),
    ]

    operations = [
        migrations.AlterField(
            model_name='class',
            name='class_type',
            field=models.CharField(choices=[('GROUP', 'Group'), ('INDIVIDUAL', 'Individual')], db_index=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='class',
            name='is_active',
            field=models.BooleanField(db_index=True, default=True),
        ),
        migrations.AlterField(
            model_name='enrollment',
            name='enrolled_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='enrollment',
            name='status',
            field=models.CharField(choices=[('PENDING_PAYMENT', 'Pending Payment'), ('ACTIVE', 'Active'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled')], db_index=True, default='PENDING_PAYMENT', max_length=20),
        ),
        migrations.AlterField(
            model_name='enrollmentpayment',
            name='payment_date',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='enrollmentpayment',
            name='payment_method',
            field=models.CharField(choices=[('CASH', 'Cash'), ('ONLINE', 'Online')], db_index=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='enrollmentpayment',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('PAID', 'Paid'), ('FAILED', 'Failed'), ('REFUNDED', 'Refunded'), ('CANCELLED', 'Cancelled')], db_index=True, default='PENDING', max_length=20),
        ),
        migrations.AlterField(
            model_name='enrollmentperiod',
            name='class_type',
            field=models.CharField(choices=[('GROUP', 'Group'), ('INDIVIDUAL', 'Individual')], db_index=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='enrollmentperiod',
            name='end_date',
            field=models.DateField(db_index=True),
        ),
        migrations.AlterField(
            model_name='enrollmentperiod',
            name='is_active',
            field=models.BooleanField(db_index=True, default=True),
        ),
        migrations.AlterField(
            model_name='enrollmentperiod',
            name='start_date',
            field=models.DateField(db_index=True),
        ),
        migrations.AlterField(
            model_name='learningmilestone',
            name='is_active',
            field=models.BooleanField(db_index=True, default=True),
        ),
        migrations.AlterField(
            model_name='program',
            name='is_active',
            field=models.BooleanField(db_index=True, default=True),
        ),
        migrations.AlterField(
            model_name='staffattendancerecord',
            name='status',
            field=models.CharField(choices=[('PRESENT', 'Present'), ('ABSENT', 'Absent'), ('LATE', 'Late'), ('EXCUSED', 'Excused')], db_index=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='staffattendancesession',
            name='date',
            field=models.DateField(db_index=True),
        ),
        migrations.AlterField(
            model_name='staffattendancesession',
            name='is_active',
            field=models.BooleanField(db_index=True, default=True),
        ),
        migrations.AlterField(
            model_name='staffattendancesession',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'Draft'), ('PUBLISHED', 'Published')], db_index=True, default='DRAFT', max_length=10),
        ),
        migrations.AlterField(
            model_name='student',
            name='date_joined',
            field=models.DateField(db_index=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='is_active',
            field=models.BooleanField(db_index=True, default=True),
        ),
        migrations.AlterField(
            model_name='studentprogress',
            name='status',
            field=models.CharField(choices=[('NOT_STARTED', 'Not Started'), ('IN_PROGRESS', 'In Progress'), ('COMPLETED', 'Completed')], db_index=True, default='NOT_STARTED', max_length=20),
        ),
        migrations.AlterField(
            model_name='subprogram',
            name='is_active',
            field=models.BooleanField(db_index=True, default=True),
        ),
    ]
