# Generated by Django 5.2.15 on 2026-07-15 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academic', '0016_payment_verification_overhaul'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subprogram',
            name='individual_fee',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
