# Generated by Django 5.2.15 on 2026-07-15 20:38

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academic', '0017_alter_subprogram_individual_fee'),
        ('accounts', '0005_alter_userassignment_role'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='enrollment',
            name='transferred_from',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transferred_to_enrollments', to='academic.enrollment'),
        ),
        migrations.CreateModel(
            name='BranchTransferRequest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], db_index=True, default='PENDING', max_length=20)),
                ('rejection_reason', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='approved_transfer_requests', to=settings.AUTH_USER_MODEL)),
                ('enrollment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='branch_transfer_requests', to='academic.enrollment')),
                ('from_branch', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='outgoing_transfer_requests', to='accounts.branch')),
                ('requested_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='initiated_transfer_requests', to=settings.AUTH_USER_MODEL)),
                ('target_class', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='incoming_transfer_requests', to='academic.class')),
                ('to_branch', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='incoming_transfer_requests', to='accounts.branch')),
            ],
            options={
                'db_table': 'academic_branch_transfer_request',
                'ordering': ['-created_at'],
            },
        ),
    ]
