# Generated by Django 5.2.1 on 2026-07-16 21:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academic', '0018_enrollment_transferred_from_branchtransferrequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='program',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='program_images/'),
        ),
        migrations.AddField(
            model_name='subprogram',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='sub_program_images/'),
        ),
    ]
