# Generated by Django 5.2.1 on 2026-07-17 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academic', '0019_add_program_subprogram_image'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='enrollment',
            name='unique_active_enrollment_per_student_class',
        ),
        migrations.AddConstraint(
            model_name='enrollment',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'ACTIVE')), fields=('student', 'enrolled_class'), name='unique_active_enrollment_per_student_class'),
        ),
    ]
