# Generated by Django 5.2.15 on 2026-07-21 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academic', '0020_fix_unique_constraint_active_only'),
    ]

    operations = [
        migrations.AddField(
            model_name='enrollment',
            name='email_verification_otp',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='enrollment',
            name='email_verification_otp_expiry',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='enrollment',
            name='email_verified',
            field=models.BooleanField(default=False),
        ),
    ]
