# Generated by Django 5.2.15 on 2026-07-21 13:00

import apps.shared.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academic', '0022_add_transaction_ref_unique_constraint'),
    ]

    operations = [
        migrations.AlterField(
            model_name='branchtransferrequest',
            name='enrollment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='branch_transfer_requests', to='academic.enrollment'),
        ),
        migrations.AlterField(
            model_name='enrollmentpayment',
            name='attachment',
            field=models.FileField(blank=True, null=True, upload_to='payment_attachments/', validators=[apps.shared.validators.UploadedFileValidator()]),
        ),
    ]
