# Generated by Django 5.2.15 on 2026-07-21 14:28

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academic', '0023_alter_branchtransferrequest_enrollment_and_more'),
        ('accounts', '0007_alter_user_profile_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendancerecord',
            name='remarks',
            field=models.TextField(blank=True, default='', validators=[django.core.validators.MaxLengthValidator(2000)]),
        ),
        migrations.AlterField(
            model_name='branchtransferrequest',
            name='rejection_reason',
            field=models.TextField(blank=True, default='', validators=[django.core.validators.MaxLengthValidator(2000)]),
        ),
        migrations.AlterField(
            model_name='enrollment',
            name='rejection_reason',
            field=models.TextField(blank=True, default='', validators=[django.core.validators.MaxLengthValidator(2000)]),
        ),
        migrations.AlterField(
            model_name='enrollment',
            name='remarks',
            field=models.TextField(blank=True, default='', validators=[django.core.validators.MaxLengthValidator(2000)]),
        ),
        migrations.AlterField(
            model_name='enrollmentpayment',
            name='verification_notes',
            field=models.TextField(blank=True, default='', validators=[django.core.validators.MaxLengthValidator(2000)]),
        ),
        migrations.AlterField(
            model_name='staffattendancerecord',
            name='notes',
            field=models.TextField(blank=True, default='', validators=[django.core.validators.MaxLengthValidator(2000)]),
        ),
        migrations.AlterField(
            model_name='staffattendancesession',
            name='notes',
            field=models.TextField(blank=True, default='', validators=[django.core.validators.MaxLengthValidator(2000)]),
        ),
        migrations.AlterField(
            model_name='studentprogress',
            name='remarks',
            field=models.TextField(blank=True, default='', validators=[django.core.validators.MaxLengthValidator(2000)]),
        ),
        migrations.AddConstraint(
            model_name='enrollmentperiod',
            constraint=models.CheckConstraint(condition=models.Q(('end_date__gte', models.F('start_date'))), name='enrollment_period_dates_valid'),
        ),
    ]
