# Generated by Django 5.2.15 on 2026-07-10 07:42

import apps.events.models.event
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0005_alter_userassignment_role'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(db_index=True, max_length=255)),
                ('description', models.TextField()),
                ('banner', models.ImageField(blank=True, null=True, upload_to=apps.events.models.event.event_banner_upload_to)),
                ('location', models.CharField(max_length=255)),
                ('event_type', models.CharField(choices=[('GENERAL', 'General'), ('TOURNAMENT', 'Tournament'), ('WORKSHOP', 'Workshop')], db_index=True, default='GENERAL', max_length=20)),
                ('start_datetime', models.DateTimeField(db_index=True)),
                ('end_datetime', models.DateTimeField(db_index=True)),
                ('visibility', models.CharField(choices=[('PUBLIC', 'Public'), ('PRIVATE', 'Private')], db_index=True, default='PUBLIC', max_length=20)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('PUBLISHED', 'Published'), ('CANCELLED', 'Cancelled'), ('COMPLETED', 'Completed')], db_index=True, default='DRAFT', max_length=20)),
                ('registration_enabled', models.BooleanField(default=False)),
                ('registration_mode', models.CharField(blank=True, choices=[('NONE', 'None'), ('PUBLIC', 'Public'), ('STUDENT', 'Student'), ('SUBPROGRAM_STUDENT', 'Sub Program Student')], max_length=20, null=True)),
                ('registration_deadline', models.DateTimeField(blank=True, null=True)),
                ('payment_required', models.BooleanField(default=False)),
                ('registration_fee', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('capacity', models.PositiveIntegerField(blank=True, null=True)),
                ('enrolled_count', models.PositiveIntegerField(default=0)),
                ('youtube_live_url', models.URLField(blank=True, max_length=500, null=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('branch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='events', to='accounts.branch')),
            ],
            options={
                'db_table': 'events_event',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['status', 'visibility'], name='events_even_status_0bf48b_idx'), models.Index(fields=['branch', 'start_datetime'], name='events_even_branch__f67032_idx'), models.Index(fields=['branch', 'status'], name='events_even_branch__d51f71_idx')],
            },
        ),
    ]
