# Generated by Django 5.2.15 on 2026-07-10 08:17

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tournament',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('category', models.CharField(choices=[('VEX_IQ', 'VEX IQ'), ('VEX_V5', 'VEX V5'), ('ENJOY_AI', 'Enjoy AI')], db_index=True, max_length=20)),
                ('max_teams', models.PositiveIntegerField(blank=True, null=True)),
                ('prize_pool', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('is_closed', models.BooleanField(db_index=True, default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('event', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='tournament', to='events.event')),
            ],
            options={
                'db_table': 'events_tournament',
                'ordering': ['-created_at'],
            },
        ),
    ]
