# Generated by Django 5.2.15 on 2026-07-10 08:49

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0004_tournamentteam'),
    ]

    operations = [
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('round', models.CharField(max_length=100)),
                ('scheduled_at', models.DateTimeField()),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('SCHEDULED', 'Scheduled'), ('LIVE', 'Live'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled')], default='SCHEDULED', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tournament', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matches', to='events.tournament')),
            ],
            options={
                'db_table': 'events_match',
                'ordering': ['-scheduled_at'],
            },
        ),
        migrations.CreateModel(
            name='MatchSide',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('side', models.CharField(choices=[('SIDE_A', 'Side A'), ('SIDE_B', 'Side B')], max_length=20)),
                ('score', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('match', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sides', to='events.match')),
            ],
            options={
                'db_table': 'events_match_side',
                'ordering': ['side'],
            },
        ),
        migrations.CreateModel(
            name='MatchParticipant',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('tournament_team', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='match_participants', to='events.tournamentteam')),
                ('match_side', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participants', to='events.matchside')),
            ],
            options={
                'db_table': 'events_match_participant',
                'ordering': ['created_at'],
            },
        ),
        migrations.AddField(
            model_name='match',
            name='winning_side',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='won_matches', to='events.matchside'),
        ),
        migrations.AddConstraint(
            model_name='matchside',
            constraint=models.UniqueConstraint(fields=('match', 'side'), name='uq_match_side'),
        ),
        migrations.AddIndex(
            model_name='matchparticipant',
            index=models.Index(fields=['tournament_team'], name='events_matc_tournam_91b087_idx'),
        ),
        migrations.AddIndex(
            model_name='matchparticipant',
            index=models.Index(fields=['match_side'], name='events_matc_match_s_6f5ffe_idx'),
        ),
        migrations.AddConstraint(
            model_name='matchparticipant',
            constraint=models.UniqueConstraint(fields=('match_side', 'tournament_team'), name='uq_match_side_team'),
        ),
        migrations.AddIndex(
            model_name='match',
            index=models.Index(fields=['tournament', 'round'], name='events_matc_tournam_1e11cf_idx'),
        ),
        migrations.AddIndex(
            model_name='match',
            index=models.Index(fields=['tournament', 'status'], name='events_matc_tournam_fdf010_idx'),
        ),
        migrations.AddIndex(
            model_name='match',
            index=models.Index(fields=['scheduled_at'], name='events_matc_schedul_8fd1cb_idx'),
        ),
        migrations.AddIndex(
            model_name='match',
            index=models.Index(fields=['status'], name='events_matc_status_79b51f_idx'),
        ),
    ]
