# Generated by Django 5.2.15 on 2026-07-10 10:20

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0007_eventregistration_tournamentteam_registration_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventPayment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('payment_method', models.CharField(choices=[('CASH', 'Cash'), ('ONLINE', 'Online')], db_index=True, max_length=10)),
                ('payment_provider', models.CharField(blank=True, choices=[('CHAPA', 'Chapa'), ('STRIPE', 'Stripe')], max_length=10, null=True)),
                ('transaction_reference', models.CharField(blank=True, db_index=True, max_length=255, null=True)),
                ('payment_date', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('PAID', 'Paid'), ('FAILED', 'Failed'), ('CANCELLED', 'Cancelled'), ('REFUNDED', 'Refunded')], db_index=True, default='PENDING', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('registration', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='payment', to='events.eventregistration')),
            ],
            options={
                'db_table': 'events_event_payment',
                'ordering': ['-created_at'],
            },
        ),
    ]
