# Generated by Django 5.2.15 on 2026-07-10 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_alter_userassignment_role'),
        ('events', '0008_eventpayment'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='eventregistration',
            name='events_even_event_i_dbc000_idx',
        ),
        migrations.RemoveIndex(
            model_name='matchparticipant',
            name='events_matc_tournam_91b087_idx',
        ),
        migrations.RemoveIndex(
            model_name='matchparticipant',
            name='events_matc_match_s_6f5ffe_idx',
        ),
        migrations.RemoveIndex(
            model_name='tournamentteam',
            name='events_tour_tournam_f558b9_idx',
        ),
        migrations.AddIndex(
            model_name='event',
            index=models.Index(fields=['status', 'visibility', 'is_active'], name='events_even_status_fc32ab_idx'),
        ),
        migrations.AddIndex(
            model_name='tournamentteam',
            index=models.Index(fields=['tournament', 'points', 'wins'], name='events_tour_tournam_383e00_idx'),
        ),
    ]
