# Generated by Django 5.2.15 on 2026-07-16 06:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0009_phase11_indexes'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='eventpayment',
            name='payment_provider',
        ),
        migrations.AddField(
            model_name='eventpayment',
            name='attachment',
            field=models.FileField(blank=True, null=True, upload_to='payment_attachments/'),
        ),
        migrations.AddField(
            model_name='eventpayment',
            name='bank_name',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='eventpayment',
            name='verification_notes',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='eventpayment',
            name='verified_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='eventpayment',
            name='verified_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='verified_event_payments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='eventpayment',
            name='payment_method',
            field=models.CharField(choices=[('CASH', 'Cash'), ('BANK_TRANSFER', 'Bank Transfer'), ('MOBILE_MONEY', 'Mobile Money'), ('CHEQUE', 'Cheque')], db_index=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='eventpayment',
            name='status',
            field=models.CharField(choices=[('PENDING_VERIFICATION', 'Pending Verification'), ('VERIFIED', 'Verified'), ('REJECTED', 'Rejected'), ('CANCELLED', 'Cancelled')], db_index=True, default='PENDING_VERIFICATION', max_length=20),
        ),
        migrations.AlterField(
            model_name='eventpayment',
            name='transaction_reference',
            field=models.CharField(blank=True, db_index=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='eventregistration',
            name='payment_status',
            field=models.CharField(choices=[('PENDING_VERIFICATION', 'Pending Verification'), ('VERIFIED', 'Verified'), ('REJECTED', 'Rejected'), ('CANCELLED', 'Cancelled')], db_index=True, default='PENDING_VERIFICATION', max_length=20),
        ),
    ]
