# Generated by Django 5.2.15 on 2026-07-19 10:53

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0010_remove_eventpayment_payment_provider_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventregistration',
            name='email_verification_otp',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='eventregistration',
            name='email_verification_otp_expiry',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='eventpayment',
            name='attachment',
            field=models.FileField(blank=True, null=True, upload_to='payment_attachments/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'png', 'jpg', 'jpeg', 'gif']), django.core.validators.MaxValueValidator(5242880)]),
        ),
        migrations.AlterField(
            model_name='eventregistration',
            name='registration_status',
            field=models.CharField(choices=[('PENDING_EMAIL_VERIFICATION', 'Pending Email Verification'), ('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('CANCELLED', 'Cancelled')], db_index=True, default='PENDING', max_length=30),
        ),
    ]
