# Generated by Django 5.2.15 on 2026-07-20 06:15

import apps.events.models.event
import apps.events.models.event_payment
import apps.shared.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0011_event_registration_otp_and_file_validators'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='banner',
            field=models.ImageField(blank=True, null=True, upload_to=apps.events.models.event.event_banner_upload_to, validators=[apps.shared.validators.UploadedFileValidator()]),
        ),
        migrations.AlterField(
            model_name='eventpayment',
            name='attachment',
            field=models.FileField(blank=True, null=True, upload_to=apps.events.models.event_payment.payment_attachment_upload_to, validators=[apps.shared.validators.UploadedFileValidator()]),
        ),
    ]
