# Generated by Django 5.2.15 on 2026-07-11 16:33

import apps.cms.models.map_node
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MapNode',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('city', models.CharField(max_length=200)),
                ('country', models.CharField(max_length=200)),
                ('title', models.CharField(max_length=300)),
                ('achievement', models.TextField()),
                ('x', models.FloatField(help_text='Map position as percentage (0–100)')),
                ('y', models.FloatField(help_text='Map position as percentage (0–100)')),
                ('lat', models.CharField(blank=True, default='', help_text='e.g. "8.9806° N"', max_length=50)),
                ('lng', models.CharField(blank=True, default='', help_text='e.g. "38.7578° E"', max_length=50)),
                ('image', models.ImageField(blank=True, null=True, upload_to=apps.cms.models.map_node.map_node_upload_to)),
                ('category', models.CharField(choices=[('CHAMPIONSHIP', 'Championship'), ('ACADEMIC', 'Academic'), ('RESEARCH', 'Research'), ('STRATEGY', 'Strategy'), ('ALLIANCE', 'Alliance')], db_index=True, max_length=20)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'cms_map_node',
                'ordering': ['title'],
            },
        ),
    ]
