# Generated by Django 5.2.15 on 2026-07-14 12:10

import apps.cms.models.gallery
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0002_mapnode'),
    ]

    operations = [
        migrations.CreateModel(
            name='Gallery',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=300)),
                ('description', models.TextField(blank=True, default='')),
                ('image', models.ImageField(blank=True, null=True, upload_to=apps.cms.models.gallery.gallery_upload_to)),
                ('video_url', models.URLField(blank=True, max_length=500, null=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'cms_gallery',
                'ordering': ['-created_at'],
            },
        ),
    ]
