# Generated by Django 5.2.1 on 2026-07-15 19:35

import apps.cms.models.about
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0003_gallery'),
    ]

    operations = [
        migrations.AddField(
            model_name='aboutus',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=apps.cms.models.about.about_upload_to),
        ),
        migrations.AddField(
            model_name='aboutus',
            name='mission',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='aboutus',
            name='vision',
            field=models.TextField(blank=True, default=''),
        ),
    ]
