# Generated by Django 5.2.15 on 2026-07-19 13:29

import apps.cms.models.about
import apps.cms.models.gallery
import apps.cms.models.hero_banner
import apps.cms.models.map_node
import apps.cms.models.news
import apps.cms.models.partner
import apps.shared.validators
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0004_aboutus_image_aboutus_mission_aboutus_vision'),
    ]

    operations = [
        migrations.CreateModel(
            name='HomepageStatistic',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('future_engineers', models.PositiveIntegerField(default=5000000, help_text='Target number of future engineers')),
                ('programs', models.PositiveIntegerField(default=120, help_text='Number of programs')),
                ('competitions', models.PositiveIntegerField(default=500, help_text='Number of competitions')),
                ('mission_current', models.PositiveIntegerField(default=1240500, help_text='Current progress toward mission target')),
                ('mission_target', models.PositiveIntegerField(default=5000000, help_text='Mission target value')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Homepage Statistic',
                'verbose_name_plural': 'Homepage Statistics',
                'db_table': 'cms_homepage_statistic',
            },
        ),
        migrations.CreateModel(
            name='Testimonial',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('role', models.CharField(help_text='e.g. Parent, Student, Partner', max_length=100)),
                ('quote', models.TextField()),
                ('image', models.URLField(blank=True, max_length=500, null=True, validators=[apps.shared.validators.HttpsUrlValidator()])),
                ('video_url', models.URLField(blank=True, max_length=500, null=True, validators=[apps.shared.validators.HttpsUrlValidator()])),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('order', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'cms_testimonial',
                'ordering': ['order'],
            },
        ),
        migrations.AlterField(
            model_name='aboutus',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=apps.cms.models.about.about_upload_to, validators=[apps.shared.validators.UploadedFileValidator()]),
        ),
        migrations.AlterField(
            model_name='gallery',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=apps.cms.models.gallery.gallery_upload_to, validators=[apps.shared.validators.UploadedFileValidator()]),
        ),
        migrations.AlterField(
            model_name='gallery',
            name='video_url',
            field=models.URLField(blank=True, max_length=500, null=True, validators=[apps.shared.validators.HttpsUrlValidator()]),
        ),
        migrations.AlterField(
            model_name='herobanner',
            name='button_url',
            field=models.URLField(blank=True, max_length=500, null=True, validators=[apps.shared.validators.HttpsUrlValidator()]),
        ),
        migrations.AlterField(
            model_name='herobanner',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=apps.cms.models.hero_banner.hero_banner_upload_to, validators=[apps.shared.validators.UploadedFileValidator()]),
        ),
        migrations.AlterField(
            model_name='herobanner',
            name='video_url',
            field=models.URLField(blank=True, max_length=500, null=True, validators=[apps.shared.validators.HttpsUrlValidator()]),
        ),
        migrations.AlterField(
            model_name='mapnode',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=apps.cms.models.map_node.map_node_upload_to, validators=[apps.shared.validators.UploadedFileValidator()]),
        ),
        migrations.AlterField(
            model_name='newsarticle',
            name='button_url',
            field=models.URLField(blank=True, max_length=500, null=True, validators=[apps.shared.validators.HttpsUrlValidator()]),
        ),
        migrations.AlterField(
            model_name='newsarticle',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=apps.cms.models.news.news_upload_to, validators=[apps.shared.validators.UploadedFileValidator()]),
        ),
        migrations.AlterField(
            model_name='newsarticle',
            name='video_url',
            field=models.URLField(blank=True, max_length=500, null=True, validators=[apps.shared.validators.HttpsUrlValidator()]),
        ),
        migrations.AlterField(
            model_name='partner',
            name='image',
            field=models.ImageField(upload_to=apps.cms.models.partner.partner_upload_to, validators=[apps.shared.validators.UploadedFileValidator()]),
        ),
        migrations.AlterField(
            model_name='partner',
            name='website_url',
            field=models.URLField(blank=True, max_length=500, null=True, validators=[apps.shared.validators.HttpsUrlValidator()]),
        ),
    ]
