# Generated by Django 5.2.15 on 2026-07-20 06:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0005_homepagestatistic_testimonial_alter_aboutus_image_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='homepagestatistic',
            options={'ordering': ['-created_at'], 'verbose_name': 'Homepage Statistic', 'verbose_name_plural': 'Homepage Statistics'},
        ),
    ]
