from django.urls import path

from apps.academic.views import (
    AdmitStudentView,
    AttendanceSessionDetailView,
    AttendanceSessionListCreateView,
    AttendanceRecordDetailView,
    AttendanceReportView,
    AvailableStaffView,
    CertificatePublicVerifyView,
    CertificateReportView,
    CertificateTemplateActivateView,
    CertificateTemplateDeactivateView,
    CertificateTemplateListCreateView,
    CertificateTemplateRetrieveUpdateView,
    ClassActivateView,
    ClassAssignInstructorView,
    ClassDeactivateView,
    ClassListCreateView,
    ClassReportView,
    ClassRetrieveUpdateView,
    EnrollmentAttendanceHistoryView,
    EnrollmentAttendanceSummaryView,
    EnrollmentCancelView,
    EnrollmentCompleteView,
    EnrollmentListCreateView,
    EnrollmentPeriodActivateView,
    EnrollmentPeriodDeactivateView,
    EnrollmentPeriodListCreateView,
    EnrollmentPeriodRetrieveUpdateView,
    EnrollmentReportView,
    MaterialDeleteView,
    MaterialDownloadView,
    MaterialListCreateView,
    MaterialRetrieveUpdateView,
    MilestoneArchiveView,
    MilestoneCustomizeView,
    MilestoneListCreateView,
    MilestoneRetrieveUpdateView,
    OnlineEnrollmentView,
    PaymentCreateView,
    PaymentListView,
    EnrollmentVerificationQueueView,
    EnrollmentUnderReviewView,
    EnrollmentRejectView,
    ProgramActivateView,
    ProgramDeactivateView,
    ProgramListCreateView,
    ProgramReportView,
    ProgramRetrieveUpdateView,
    ProgressHistoryView,
    ProgressReportView,
    ProgressSummaryView,
    RecordDetailView,
    RecordProgressView,
    RecordUpsertView,
    SessionDetailView,
    SessionListCreateView,
    SessionPublishView,
    SessionRecordBulkView,
    StudentAcademicReportView,
    StudentActivateView,
    StudentCertificateIssueView,
    StudentCertificateListView,
    StudentCertificateRetrieveView,
    StudentDeactivateView,
    StudentListView,
    StudentRetrieveUpdateView,
    StudentSearchView,
    SubProgramActivateView,
    SubProgramDeactivateView,
    SubProgramListCreateView,
    SubProgramReportView,
    SubProgramRetrieveUpdateView,
    UpdateProgressView,
)
from apps.academic.views.enrollment_move import EnrollmentMoveView, ClassSplitView
from apps.academic.views.transfer_views import (
    BranchTransferApproveView,
    BranchTransferListView,
    BranchTransferRejectView,
    BranchTransferRequestView,
    EnrollmentSwitchSubProgramView,
)

urlpatterns = [
    # Program
    path("programs/", ProgramListCreateView.as_view(), name="program-list-create"),
    path("programs/<uuid:pk>/", ProgramRetrieveUpdateView.as_view(), name="program-retrieve-update"),
    path("programs/<uuid:pk>/activate/", ProgramActivateView.as_view(), name="program-activate"),
    path("programs/<uuid:pk>/deactivate/", ProgramDeactivateView.as_view(), name="program-deactivate"),
    # Sub Program
    path("sub-programs/", SubProgramListCreateView.as_view(), name="sub-program-list-create"),
    path("sub-programs/<uuid:pk>/", SubProgramRetrieveUpdateView.as_view(), name="sub-program-retrieve-update"),
    path("sub-programs/<uuid:pk>/activate/", SubProgramActivateView.as_view(), name="sub-program-activate"),
    path("sub-programs/<uuid:pk>/deactivate/", SubProgramDeactivateView.as_view(), name="sub-program-deactivate"),
    # Class
    path("classes/", ClassListCreateView.as_view(), name="class-list-create"),
    path("classes/<uuid:pk>/", ClassRetrieveUpdateView.as_view(), name="class-retrieve-update"),
    path("classes/<uuid:pk>/assign-instructor/", ClassAssignInstructorView.as_view(), name="class-assign-instructor"),
    path("classes/<uuid:pk>/activate/", ClassActivateView.as_view(), name="class-activate"),
    path("classes/<uuid:pk>/deactivate/", ClassDeactivateView.as_view(), name="class-deactivate"),
    # Admission
    path("admissions/", AdmitStudentView.as_view(), name="admit-student"),
    # Student
    path("students/", StudentListView.as_view(), name="student-list"),
    path("students/search/", StudentSearchView.as_view(), name="student-search"),
    path("students/<uuid:pk>/", StudentRetrieveUpdateView.as_view(), name="student-retrieve-update"),
    path("students/<uuid:pk>/activate/", StudentActivateView.as_view(), name="student-activate"),
    path("students/<uuid:pk>/deactivate/", StudentDeactivateView.as_view(), name="student-deactivate"),
    # Enrollment Period
    path("enrollment-periods/", EnrollmentPeriodListCreateView.as_view(), name="enrollment-period-list-create"),
    path("enrollment-periods/<uuid:pk>/", EnrollmentPeriodRetrieveUpdateView.as_view(), name="enrollment-period-retrieve-update"),
    path("enrollment-periods/<uuid:pk>/activate/", EnrollmentPeriodActivateView.as_view(), name="enrollment-period-activate"),
    path("enrollment-periods/<uuid:pk>/deactivate/", EnrollmentPeriodDeactivateView.as_view(), name="enrollment-period-deactivate"),
    # Staff Attendance
    path("staff-attendance/sessions/available-staff/", AvailableStaffView.as_view(), name="staff-attendance-available-staff"),
    path("staff-attendance/sessions/", SessionListCreateView.as_view(), name="staff-attendance-session-list-create"),
    path("staff-attendance/sessions/<uuid:pk>/", SessionDetailView.as_view(), name="staff-attendance-session-detail"),
    path("staff-attendance/sessions/<uuid:pk>/publish/", SessionPublishView.as_view(), name="staff-attendance-session-publish"),
    path("staff-attendance/sessions/<uuid:pk>/records/", RecordUpsertView.as_view(), name="staff-attendance-record-upsert"),
    path("staff-attendance/sessions/<uuid:pk>/records/<uuid:record_pk>/", RecordDetailView.as_view(), name="staff-attendance-record-detail"),
    # Enrollment
    path("enrollments/", EnrollmentListCreateView.as_view(), name="enrollment-list-create"),
    path("enrollments/<uuid:pk>/cancel/", EnrollmentCancelView.as_view(), name="enrollment-cancel"),
    path("enrollments/<uuid:pk>/complete/", EnrollmentCompleteView.as_view(), name="enrollment-complete"),
    path("enrollments/online/", OnlineEnrollmentView.as_view(), name="enrollment-online"),
    path("enrollments/<uuid:pk>/move/", EnrollmentMoveView.as_view(), name="enrollment-move"),
    # Class Split
    path("classes/<uuid:pk>/split/", ClassSplitView.as_view(), name="class-split"),
    # Payments
    path("payments/", PaymentCreateView.as_view(), name="payment-create"),
    path("payments/list/", PaymentListView.as_view(), name="payment-list"),
    path("payments/verification-queue/", EnrollmentVerificationQueueView.as_view(), name="payment-verification-queue"),
    path("payments/<uuid:pk>/under-review/", EnrollmentUnderReviewView.as_view(), name="payment-under-review"),
    path("payments/<uuid:pk>/reject/", EnrollmentRejectView.as_view(), name="payment-reject"),
    # Learning Milestones
    path("learning-milestones/", MilestoneListCreateView.as_view(), name="milestone-list-create"),
    path("learning-milestones/<uuid:pk>/", MilestoneRetrieveUpdateView.as_view(), name="milestone-retrieve-update"),
    path("learning-milestones/<uuid:pk>/archive/", MilestoneArchiveView.as_view(), name="milestone-archive"),
    path("learning-milestones/<uuid:pk>/customize/", MilestoneCustomizeView.as_view(), name="milestone-customize"),
    # Student Progress
    path("student-progress/", RecordProgressView.as_view(), name="student-progress-record"),
    path("student-progress/<uuid:pk>/", UpdateProgressView.as_view(), name="student-progress-update"),
    path("student-progress/enrollments/<uuid:enrollment_pk>/history/", ProgressHistoryView.as_view(), name="student-progress-history"),
    path("student-progress/enrollments/<uuid:enrollment_pk>/summary/", ProgressSummaryView.as_view(), name="student-progress-summary"),
    # Learning Materials
    path("learning-materials/", MaterialListCreateView.as_view(), name="material-list-create"),
    path("learning-materials/<uuid:pk>/", MaterialRetrieveUpdateView.as_view(), name="material-retrieve-update"),
    path("learning-materials/<uuid:pk>/delete/", MaterialDeleteView.as_view(), name="material-delete"),
    path("learning-materials/<uuid:pk>/download/", MaterialDownloadView.as_view(), name="material-download"),
    # Attendance
    path("attendance/sessions/", AttendanceSessionListCreateView.as_view(), name="attendance-session-list-create"),
    path("attendance/sessions/<uuid:pk>/", AttendanceSessionDetailView.as_view(), name="attendance-session-detail"),
    path("attendance/sessions/<uuid:pk>/records/", SessionRecordBulkView.as_view(), name="attendance-session-record-bulk"),
    path("attendance/sessions/<uuid:pk>/records/<uuid:record_pk>/", AttendanceRecordDetailView.as_view(), name="attendance-record-detail"),
    path("attendance/enrollments/<uuid:enrollment_pk>/history/", EnrollmentAttendanceHistoryView.as_view(), name="attendance-enrollment-history"),
    path("attendance/enrollments/<uuid:enrollment_pk>/summary/", EnrollmentAttendanceSummaryView.as_view(), name="attendance-enrollment-summary"),
    # Certificates
    path("certificate-templates/", CertificateTemplateListCreateView.as_view(), name="cert-template-list-create"),
    path("certificate-templates/<uuid:pk>/", CertificateTemplateRetrieveUpdateView.as_view(), name="cert-template-retrieve-update"),
    path("certificate-templates/<uuid:pk>/activate/", CertificateTemplateActivateView.as_view(), name="cert-template-activate"),
    path("certificate-templates/<uuid:pk>/deactivate/", CertificateTemplateDeactivateView.as_view(), name="cert-template-deactivate"),
    path("student-certificates/issue/", StudentCertificateIssueView.as_view(), name="student-cert-issue"),
    path("student-certificates/", StudentCertificateListView.as_view(), name="student-cert-list"),
    path("student-certificates/<uuid:pk>/", StudentCertificateRetrieveView.as_view(), name="student-cert-retrieve"),
    path("certificates/verify/<str:number>/", CertificatePublicVerifyView.as_view(), name="cert-verify"),
    # Transfers
    path("transfers/request/", BranchTransferRequestView.as_view(), name="transfer-request"),
    path("transfers/", BranchTransferListView.as_view(), name="transfer-list"),
    path("transfers/<uuid:pk>/approve/", BranchTransferApproveView.as_view(), name="transfer-approve"),
    path("transfers/<uuid:pk>/reject/", BranchTransferRejectView.as_view(), name="transfer-reject"),
    path("enrollments/<uuid:pk>/switch-subprogram/", EnrollmentSwitchSubProgramView.as_view(), name="enrollment-switch-subprogram"),
    # Reports
    path("reports/students/<uuid:pk>/academic/", StudentAcademicReportView.as_view(), name="report-student-academic"),
    path("reports/students/<uuid:pk>/enrollments/", EnrollmentReportView.as_view(), name="report-student-enrollments"),
    path("reports/students/<uuid:pk>/attendance/", AttendanceReportView.as_view(), name="report-student-attendance"),
    path("reports/students/<uuid:pk>/progress/", ProgressReportView.as_view(), name="report-student-progress"),
    path("reports/students/<uuid:pk>/certificates/", CertificateReportView.as_view(), name="report-student-certificates"),
    path("reports/classes/<uuid:pk>/", ClassReportView.as_view(), name="report-class"),
    path("reports/sub-programs/<uuid:pk>/", SubProgramReportView.as_view(), name="report-sub-program"),
    path("reports/programs/<uuid:pk>/", ProgramReportView.as_view(), name="report-program"),
]
