"""Abstract base class for payment providers.

Defines the contract that every concrete payment provider must implement.
The ``PaymentService`` dispatches to the active provider through this
interface, keeping business modules decoupled from provider specifics.

All money values use ``Decimal`` — never ``float``.  Both ``callback_url``
(server-to-server webhook) and ``return_url`` (browser redirect after
payment) are supported.
"""

from abc import ABC, abstractmethod
from decimal import Decimal
from typing import Optional

from apps.shared.payment.types import InitializationResponse, VerificationResponse


class BasePaymentProvider(ABC):
    """Abstract payment provider interface.

    Concrete subclasses must implement ``initialize()`` and ``verify()``
    for their respective payment gateway.  All responses **must** conform
    to the normalised ``TypedDict`` shapes defined in ``types.py``.
    """

    @abstractmethod
    def initialize(
        self,
        amount: Decimal,
        currency: str,
        reference: str,
        callback_url: str,
        customer: dict,
        return_url: Optional[str] = None,
    ) -> InitializationResponse:
        """Initialize a payment transaction with the provider.

        Args:
            amount: Payment amount as a ``Decimal``.
            currency: ISO 4217 currency code (e.g. ``"ETB"``, ``"USD"``).
            reference: Unique transaction reference generated by the
                calling business service.
            callback_url: Server-to-server URL for the provider to
                notify on payment completion.
            customer: Dictionary with at least ``email`` and optionally
                ``first_name``, ``last_name``, ``phone_number``.
            return_url: Optional browser redirect URL after the user
                completes payment on the provider's checkout page.

        Returns:
            Normalised ``InitializationResponse`` dict.

        Raises:
            PaymentProviderError: On infrastructure failure.
        """

    @abstractmethod
    def verify(self, reference: str) -> VerificationResponse:
        """Verify a payment transaction by reference.

        Args:
            reference: The transaction reference to verify.

        Returns:
            Normalised ``VerificationResponse`` dict.

        Raises:
            PaymentProviderError: On infrastructure failure.
        """
