# Generated by Django 5.2.15 on 2026-07-13 07:40

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_alter_userassignment_role'),
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BranchInventory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('quantity', models.IntegerField(default=0)),
                ('minimum_quantity', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='store_inventory', to='accounts.branch')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventory_records', to='store.product')),
            ],
            options={
                'verbose_name_plural': 'Branch inventories',
                'db_table': 'store_branch_inventory',
                'constraints': [models.CheckConstraint(condition=models.Q(('quantity__gte', 0)), name='inventory_quantity_gte_zero')],
                'unique_together': {('branch', 'product')},
            },
        ),
    ]
