# Generated by Django 5.2.15 on 2026-07-13 08:18

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_alter_userassignment_role'),
        ('store', '0002_branchinventory'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ShoppingCart',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('session_key', models.CharField(blank=True, max_length=255, null=True)),
                ('expires_at', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='shopping_carts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'store_shopping_cart',
            },
        ),
        migrations.CreateModel(
            name='ShoppingCartItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('quantity', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cart_items', to='accounts.branch')),
                ('cart', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='store.shoppingcart')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cart_items', to='store.product')),
            ],
            options={
                'db_table': 'store_shopping_cart_item',
            },
        ),
        migrations.AddIndex(
            model_name='shoppingcart',
            index=models.Index(fields=['user'], name='sc_user_idx'),
        ),
        migrations.AddIndex(
            model_name='shoppingcart',
            index=models.Index(fields=['session_key'], name='sc_session_key_idx'),
        ),
        migrations.AddIndex(
            model_name='shoppingcart',
            index=models.Index(fields=['expires_at'], name='sc_expires_at_idx'),
        ),
        migrations.AddIndex(
            model_name='shoppingcartitem',
            index=models.Index(fields=['cart'], name='sci_cart_idx'),
        ),
        migrations.AddIndex(
            model_name='shoppingcartitem',
            index=models.Index(fields=['product'], name='sci_product_idx'),
        ),
        migrations.AddConstraint(
            model_name='shoppingcartitem',
            constraint=models.CheckConstraint(condition=models.Q(('quantity__gt', 0)), name='cart_item_quantity_gt_zero'),
        ),
        migrations.AlterUniqueTogether(
            name='shoppingcartitem',
            unique_together={('cart', 'product', 'branch')},
        ),
    ]
