# Generated by Django 5.2.15 on 2026-07-13 08:32

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_alter_userassignment_role'),
        ('store', '0003_shopping_cart'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PendingOrder',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('payment_reference', models.CharField(blank=True, max_length=255, null=True)),
                ('subtotal', models.DecimalField(decimal_places=2, max_digits=10)),
                ('total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('guest_name', models.CharField(blank=True, default='', max_length=255)),
                ('guest_email', models.EmailField(blank=True, default='', max_length=255)),
                ('guest_phone', models.CharField(blank=True, default='', max_length=20)),
                ('expires_at', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pending_orders', to='accounts.branch')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pending_orders', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'store_pending_order',
            },
        ),
        migrations.CreateModel(
            name='PendingOrderItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('quantity', models.IntegerField()),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('subtotal', models.DecimalField(decimal_places=2, max_digits=10)),
                ('pending_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='store.pendingorder')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pending_order_items', to='store.product')),
            ],
            options={
                'db_table': 'store_pending_order_item',
            },
        ),
        migrations.AddIndex(
            model_name='pendingorder',
            index=models.Index(fields=['expires_at'], name='po_expires_at_idx'),
        ),
        migrations.AddIndex(
            model_name='pendingorder',
            index=models.Index(fields=['payment_reference'], name='po_payment_ref_idx'),
        ),
    ]
