# Generated by Django 5.2.15 on 2026-07-13 09:02

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_pending_order'),
    ]

    operations = [
        migrations.CreateModel(
            name='StorePayment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('payment_method', models.CharField(choices=[('CASH', 'Cash'), ('ONLINE', 'Online')], default='ONLINE', max_length=10)),
                ('payment_provider', models.CharField(blank=True, choices=[('CHAPA', 'Chapa'), ('STRIPE', 'Stripe')], max_length=10, null=True)),
                ('transaction_reference', models.CharField(db_index=True, max_length=255, unique=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('PAID', 'Paid'), ('FAILED', 'Failed'), ('REFUNDED', 'Refunded')], db_index=True, default='PENDING', max_length=20)),
                ('payment_date', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('pending_order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='payment', to='store.pendingorder')),
            ],
            options={
                'db_table': 'store_payment',
                'ordering': ['-created_at'],
            },
        ),
    ]
