# Generated by Django 5.2.15 on 2026-07-13 13:13

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_alter_userassignment_role'),
        ('store', '0007_order_cancelled_at_order_refunded_at_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='productcategory',
            name='is_active',
            field=models.BooleanField(db_index=True, default=True),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['status', 'created_at'], name='order_status_created_idx'),
        ),
        migrations.AddIndex(
            model_name='pendingorderitem',
            index=models.Index(fields=['pending_order'], name='poi_pending_order_idx'),
        ),
        migrations.AddIndex(
            model_name='pendingorderitem',
            index=models.Index(fields=['product'], name='poi_product_idx'),
        ),
        migrations.AddIndex(
            model_name='productimage',
            index=models.Index(fields=['product'], name='pi_product_idx'),
        ),
    ]
