# Generated by Django 5.2.15 on 2026-07-16 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0009_manual_payment_verification'),
    ]

    operations = [
        migrations.AlterField(
            model_name='storepayment',
            name='payment_method',
            field=models.CharField(choices=[('CASH', 'Cash'), ('BANK_TRANSFER', 'Bank Transfer'), ('MOBILE_MONEY', 'Mobile Money'), ('CHEQUE', 'Cheque')], db_index=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='storepayment',
            name='status',
            field=models.CharField(choices=[('PENDING_VERIFICATION', 'Pending Verification'), ('VERIFIED', 'Verified'), ('REJECTED', 'Rejected'), ('CANCELLED', 'Cancelled')], db_index=True, default='PENDING_VERIFICATION', max_length=20),
        ),
    ]
