# Generated by Django 5.2.15 on 2026-07-20 08:11

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0010_alter_payment_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='pendingorder',
            name='access_token',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
    ]
