# Generated by Django 5.2.15 on 2026-07-20 08:59

import apps.store.models.payment
import apps.store.models.product_image
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0011_pending_order_access_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='pendingorder',
            name='email_verification_otp',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='pendingorder',
            name='email_verification_otp_expiry',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pendingorder',
            name='email_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='productimage',
            name='image',
            field=models.ImageField(upload_to=apps.store.models.product_image._product_image_path),
        ),
        migrations.AlterField(
            model_name='storepayment',
            name='attachment',
            field=models.FileField(blank=True, null=True, upload_to=apps.store.models.payment._payment_attachment_path),
        ),
    ]
