# Generated by Django 5.2.15 on 2026-07-20 12:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0012_pending_order_email_verification'),
    ]

    operations = [
        migrations.AlterField(
            model_name='storepayment',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='storepayment',
            name='pending_order',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payment', to='store.pendingorder'),
        ),
    ]
