# Generated by Django 5.2.15 on 2026-07-21 13:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0013_payment_protect_and_index'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='branchinventory',
            options={'ordering': ['branch', 'product'], 'verbose_name_plural': 'Branch inventories'},
        ),
    ]
