from django.urls import path

from apps.store.api.views import (
    AdminBranchSalesReportView,
    AdminCategoryActivateView,
    AdminCategoryDeactivateView,
    AdminCategoryListCreateView,
    AdminCategoryRetrieveUpdateView,
    AdminInventoryAddView,
    AdminInventoryCorrectView,
    AdminInventoryListCreateView,
    AdminInventoryReduceView,
    AdminInventoryRetrieveUpdateView,
    AdminInventoryReportView,
    AdminInventoryTransferView,
    AdminLowStockReportView,
    AdminOrderDetailView,
    AdminOrderListView,
    AdminOrderReportView,
    AdminOrderStatusView,
    AdminPaymentCashView,
    AdminPaymentListView,
    AdminPaymentRejectView,
    AdminPaymentVerifyView,
    PaymentEvidenceSubmitView,
    AdminProductActivateView,
    AdminProductArchiveView,
    AdminProductDeactivateView,
    AdminProductImageListView,
    AdminProductImageRetrieveDestroyView,
    AdminProductImageReorderView,
    AdminProductImageSetPrimaryView,
    AdminProductImageUploadView,
    AdminProductListCreateView,
    AdminProductRestoreView,
    AdminProductRetrieveUpdateView,
    AdminProductStatisticsView,
    AdminSalesReportView,
    CartAddItemView,
    CartClearView,
    CartDetailView,
    CartItemRemoveView,
    CartItemUpdateView,
    CheckoutView,
    PendingOrderDetailView,
    PublicBranchInventoryListView,
    PublicCategoryDetailView,
    PublicCategoryListView,
    PublicProductAvailabilityView,
    PublicProductDetailView,
    PublicProductListView,
    UserOrderDetailView,
    UserOrderListView,
)

urlpatterns = [
    # Public
    path("categories/", PublicCategoryListView.as_view(), name="store-category-list"),
    path(
        "categories/<uuid:pk>/",
        PublicCategoryDetailView.as_view(),
        name="store-category-detail",
    ),
    path("products/", PublicProductListView.as_view(), name="store-product-list"),
    path(
        "products/<uuid:pk>/",
        PublicProductDetailView.as_view(),
        name="store-product-detail",
    ),
    path(
        "inventory/",
        PublicBranchInventoryListView.as_view(),
        name="store-inventory-list",
    ),
    path(
        "inventory/availability/<uuid:product_pk>/",
        PublicProductAvailabilityView.as_view(),
        name="store-inventory-availability",
    ),
    # Cart
    path("cart/", CartDetailView.as_view(), name="store-cart-detail"),
    path("cart/items/", CartAddItemView.as_view(), name="store-cart-add-item"),
    path(
        "cart/items/<uuid:pk>/",
        CartItemUpdateView.as_view(),
        name="store-cart-item-update",
    ),
    path(
        "cart/items/<uuid:pk>/remove/",
        CartItemRemoveView.as_view(),
        name="store-cart-item-remove",
    ),
    path("cart/clear/", CartClearView.as_view(), name="store-cart-clear"),
    path(
        "cart/checkout/",
        CheckoutView.as_view(),
        name="store-cart-checkout",
    ),
    path(
        "pending-orders/<uuid:pk>/",
        PendingOrderDetailView.as_view(),
        name="store-pending-order-detail",
    ),
    path(
        "pending-orders/<uuid:pending_order_pk>/evidence/",
        PaymentEvidenceSubmitView.as_view(),
        name="store-payment-evidence-submit",
    ),
    # Admin - Payments
    path(
        "admin/payments/",
        AdminPaymentListView.as_view(),
        name="store-admin-payment-list",
    ),
    path(
        "admin/pending-orders/<uuid:pending_order_pk>/verify/",
        AdminPaymentVerifyView.as_view(),
        name="store-admin-payment-verify",
    ),
    path(
        "admin/pending-orders/<uuid:pending_order_pk>/reject/",
        AdminPaymentRejectView.as_view(),
        name="store-admin-payment-reject",
    ),
    path(
        "admin/pending-orders/<uuid:pending_order_pk>/cash/",
        AdminPaymentCashView.as_view(),
        name="store-admin-payment-cash",
    ),
    # Admin - Categories
    path(
        "admin/categories/",
        AdminCategoryListCreateView.as_view(),
        name="store-admin-category-list",
    ),
    path(
        "admin/categories/<uuid:pk>/",
        AdminCategoryRetrieveUpdateView.as_view(),
        name="store-admin-category-detail",
    ),
    path(
        "admin/categories/<uuid:pk>/activate/",
        AdminCategoryActivateView.as_view(),
        name="store-admin-category-activate",
    ),
    path(
        "admin/categories/<uuid:pk>/deactivate/",
        AdminCategoryDeactivateView.as_view(),
        name="store-admin-category-deactivate",
    ),
    # Admin - Products
    path(
        "admin/products/",
        AdminProductListCreateView.as_view(),
        name="store-admin-product-list",
    ),
    path(
        "admin/products/<uuid:pk>/",
        AdminProductRetrieveUpdateView.as_view(),
        name="store-admin-product-detail",
    ),
    path(
        "admin/products/<uuid:pk>/archive/",
        AdminProductArchiveView.as_view(),
        name="store-admin-product-archive",
    ),
    path(
        "admin/products/<uuid:pk>/restore/",
        AdminProductRestoreView.as_view(),
        name="store-admin-product-restore",
    ),
    path(
        "admin/products/<uuid:pk>/activate/",
        AdminProductActivateView.as_view(),
        name="store-admin-product-activate",
    ),
    path(
        "admin/products/<uuid:pk>/deactivate/",
        AdminProductDeactivateView.as_view(),
        name="store-admin-product-deactivate",
    ),
    # Admin - Product Images
    path(
        "admin/products/<uuid:product_pk>/images/",
        AdminProductImageUploadView.as_view(),
        name="store-admin-product-image-upload",
    ),
    path(
        "admin/products/<uuid:product_pk>/images/list/",
        AdminProductImageListView.as_view(),
        name="store-admin-product-image-list",
    ),
    path(
        "admin/products/<uuid:product_pk>/images/reorder/",
        AdminProductImageReorderView.as_view(),
        name="store-admin-product-image-reorder",
    ),
    path(
        "admin/product-images/<uuid:pk>/",
        AdminProductImageRetrieveDestroyView.as_view(),
        name="store-admin-product-image-detail",
    ),
    path(
        "admin/product-images/<uuid:pk>/set-primary/",
        AdminProductImageSetPrimaryView.as_view(),
        name="store-admin-product-image-set-primary",
    ),
    # Admin - Inventory
    path(
        "admin/inventory/",
        AdminInventoryListCreateView.as_view(),
        name="store-admin-inventory-list",
    ),
    path(
        "admin/inventory/<uuid:pk>/",
        AdminInventoryRetrieveUpdateView.as_view(),
        name="store-admin-inventory-detail",
    ),
    path(
        "admin/inventory/<uuid:pk>/add/",
        AdminInventoryAddView.as_view(),
        name="store-admin-inventory-add",
    ),
    path(
        "admin/inventory/<uuid:pk>/reduce/",
        AdminInventoryReduceView.as_view(),
        name="store-admin-inventory-reduce",
    ),
    path(
        "admin/inventory/<uuid:pk>/correct/",
        AdminInventoryCorrectView.as_view(),
        name="store-admin-inventory-correct",
    ),
    path(
        "admin/inventory/transfer/",
        AdminInventoryTransferView.as_view(),
        name="store-admin-inventory-transfer",
    ),
    # Admin - Orders
    path(
        "admin/orders/",
        AdminOrderListView.as_view(),
        name="store-admin-order-list",
    ),
    path(
        "admin/orders/<uuid:pk>/",
        AdminOrderDetailView.as_view(),
        name="store-admin-order-detail",
    ),
    path(
        "admin/orders/<uuid:pk>/status/",
        AdminOrderStatusView.as_view(),
        name="store-admin-order-status",
    ),
    # Admin - Reports
    path(
        "admin/reports/products/",
        AdminProductStatisticsView.as_view(),
        name="store-admin-report-products",
    ),
    path(
        "admin/reports/inventory/",
        AdminInventoryReportView.as_view(),
        name="store-admin-report-inventory",
    ),
    path(
        "admin/reports/low-stock/",
        AdminLowStockReportView.as_view(),
        name="store-admin-report-low-stock",
    ),
    path(
        "admin/reports/sales/",
        AdminSalesReportView.as_view(),
        name="store-admin-report-sales",
    ),
    path(
        "admin/reports/orders/",
        AdminOrderReportView.as_view(),
        name="store-admin-report-orders",
    ),
    path(
        "admin/reports/branch-sales/",
        AdminBranchSalesReportView.as_view(),
        name="store-admin-report-branch-sales",
    ),
    # User - Orders
    path(
        "orders/",
        UserOrderListView.as_view(),
        name="store-user-order-list",
    ),
    path(
        "orders/<uuid:pk>/",
        UserOrderDetailView.as_view(),
        name="store-user-order-detail",
    ),
]
