from .branch_inventory import (
    AdminInventoryAddView,
    AdminInventoryCorrectView,
    AdminInventoryListCreateView,
    AdminInventoryReduceView,
    AdminInventoryRetrieveUpdateView,
    AdminInventoryTransferView,
    PublicBranchInventoryListView,
    PublicProductAvailabilityView,
)
from .category import (
    AdminCategoryActivateView,
    AdminCategoryDeactivateView,
    AdminCategoryListCreateView,
    AdminCategoryRetrieveUpdateView,
    PublicCategoryDetailView,
    PublicCategoryListView,
)
from .product import (
    AdminProductActivateView,
    AdminProductArchiveView,
    AdminProductDeactivateView,
    AdminProductListCreateView,
    AdminProductRestoreView,
    AdminProductRetrieveUpdateView,
    PublicProductDetailView,
    PublicProductListView,
)
from .product_image import (
    AdminProductImageListView,
    AdminProductImageRetrieveDestroyView,
    AdminProductImageReorderView,
    AdminProductImageSetPrimaryView,
    AdminProductImageUploadView,
)

__all__ = [
    "PublicCategoryListView",
    "PublicCategoryDetailView",
    "AdminCategoryListCreateView",
    "AdminCategoryRetrieveUpdateView",
    "AdminCategoryActivateView",
    "AdminCategoryDeactivateView",
    "PublicProductListView",
    "PublicProductDetailView",
    "AdminProductListCreateView",
    "AdminProductRetrieveUpdateView",
    "AdminProductArchiveView",
    "AdminProductRestoreView",
    "AdminProductActivateView",
    "AdminProductDeactivateView",
    "AdminProductImageUploadView",
    "AdminProductImageListView",
    "AdminProductImageRetrieveDestroyView",
    "AdminProductImageSetPrimaryView",
    "AdminProductImageReorderView",
    "PublicBranchInventoryListView",
    "PublicProductAvailabilityView",
    "AdminInventoryListCreateView",
    "AdminInventoryRetrieveUpdateView",
    "AdminInventoryAddView",
    "AdminInventoryReduceView",
    "AdminInventoryCorrectView",
    "AdminInventoryTransferView",
]
