# Generated by Django 5.2.15 on 2026-07-08 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_user_options_alter_user_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userassignment',
            name='role',
            field=models.CharField(choices=[('super_admin', 'Super Admin'), ('branch_manager', 'Branch Manager'), ('secretary', 'Secretary'), ('instructor', 'Instructor'), ('student', 'Student')], db_index=True, max_length=50),
        ),
    ]
