# Generated by Django 5.2.15 on 2026-07-20 06:24

import apps.accounts.models.user
import apps.shared.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_add_failed_login_attempts'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to=apps.accounts.models.user.profile_picture_path, validators=[apps.shared.validators.UploadedFileValidator()]),
        ),
    ]
