from apps.academic.views.program import (
    ProgramListCreateView,
    ProgramRetrieveUpdateView,
    ProgramActivateView,
    ProgramDeactivateView,
)
from apps.academic.views.sub_program import (
    SubProgramListCreateView,
    SubProgramRetrieveUpdateView,
    SubProgramActivateView,
    SubProgramDeactivateView,
)
from apps.academic.views.class_view import (
    ClassListCreateView,
    ClassRetrieveUpdateView,
    ClassAssignInstructorView,
    ClassActivateView,
    ClassDeactivateView,
)
from apps.academic.views.admission import AdmitStudentView
from apps.academic.views.student import (
    StudentListView,
    StudentRetrieveUpdateView,
    StudentSearchView,
    StudentActivateView,
    StudentDeactivateView,
)
from apps.academic.views.enrollment_period import (
    EnrollmentPeriodListCreateView,
    EnrollmentPeriodRetrieveUpdateView,
    EnrollmentPeriodActivateView,
    EnrollmentPeriodDeactivateView,
)
from apps.academic.views.staff_attendance import (
    SessionListCreateView,
    SessionDetailView,
    AvailableStaffView,
    SessionPublishView,
    RecordUpsertView,
    RecordDetailView,
)
from apps.academic.views.enrollment import (
    AvailableBranchesView,
    EnrollmentListCreateView,
    EnrollmentCancelView,
    EnrollmentCompleteView,
    OnlineEnrollmentView,
    OnlineEnrollmentVerifyEmailView,
)
from apps.academic.views.payment import (
    PaymentListView,
    PaymentCreateView,
    EnrollmentVerificationQueueView,
    EnrollmentUnderReviewView,
    EnrollmentRejectView,
)
from apps.academic.views.attendance import (
    SessionListCreateView as AttendanceSessionListCreateView,
    SessionDetailView as AttendanceSessionDetailView,
    SessionRecordBulkView,
    RecordDetailView as AttendanceRecordDetailView,
    EnrollmentAttendanceHistoryView,
    EnrollmentAttendanceSummaryView,
)
from apps.academic.views.progress import (
    MilestoneListCreateView,
    MilestoneRetrieveUpdateView,
    MilestoneArchiveView,
    MilestoneCustomizeView,
    RecordProgressView,
    UpdateProgressView,
    ProgressHistoryView,
    ProgressSummaryView,
)
from apps.academic.views.learning_material import (
    MaterialListCreateView,
    MaterialRetrieveUpdateView,
    MaterialDeleteView,
    MaterialDownloadView,
)
from apps.academic.views.certificate import (
    CertificatePublicVerifyView,
    CertificateTemplateActivateView,
    CertificateTemplateDeactivateView,
    CertificateTemplateListCreateView,
    CertificateTemplateRetrieveUpdateView,
    StudentCertificateIssueView,
    StudentCertificateListView,
    StudentCertificateRetrieveView,
)
from apps.academic.views.academic_report import (
    StudentAcademicReportView,
    EnrollmentReportView,
    AttendanceReportView,
    ProgressReportView,
    CertificateReportView,
    ClassReportView,
    SubProgramReportView,
    ProgramReportView,
)

__all__ = [
    "ProgramListCreateView",
    "ProgramRetrieveUpdateView",
    "ProgramActivateView",
    "ProgramDeactivateView",
    "SubProgramListCreateView",
    "SubProgramRetrieveUpdateView",
    "SubProgramActivateView",
    "SubProgramDeactivateView",
    "ClassListCreateView",
    "ClassRetrieveUpdateView",
    "ClassAssignInstructorView",
    "ClassActivateView",
    "ClassDeactivateView",
    "AdmitStudentView",
    "StudentListView",
    "StudentRetrieveUpdateView",
    "StudentSearchView",
    "StudentActivateView",
    "StudentDeactivateView",
    "EnrollmentPeriodListCreateView",
    "EnrollmentPeriodRetrieveUpdateView",
    "EnrollmentPeriodActivateView",
    "EnrollmentPeriodDeactivateView",
    "SessionListCreateView",
    "SessionDetailView",
    "AvailableStaffView",
    "SessionPublishView",
    "RecordUpsertView",
    "RecordDetailView",
    "EnrollmentListCreateView",
    "EnrollmentCancelView",
    "EnrollmentCompleteView",
    "AvailableBranchesView",
    "OnlineEnrollmentView",
    "OnlineEnrollmentVerifyEmailView",
    "PaymentListView",
    "PaymentCreateView",
    "EnrollmentVerificationQueueView",
    "EnrollmentUnderReviewView",
    "EnrollmentRejectView",
    "AttendanceSessionListCreateView",
    "AttendanceSessionDetailView",
    "SessionRecordBulkView",
    "AttendanceRecordDetailView",
    "EnrollmentAttendanceHistoryView",
    "EnrollmentAttendanceSummaryView",
    "MilestoneListCreateView",
    "MilestoneRetrieveUpdateView",
    "MilestoneArchiveView",
    "MilestoneCustomizeView",
    "RecordProgressView",
    "UpdateProgressView",
    "ProgressHistoryView",
    "ProgressSummaryView",
    "MaterialListCreateView",
    "MaterialRetrieveUpdateView",
    "MaterialDeleteView",
    "MaterialDownloadView",
    "CertificateTemplateListCreateView",
    "CertificateTemplateRetrieveUpdateView",
    "CertificateTemplateActivateView",
    "CertificateTemplateDeactivateView",
    "StudentCertificateIssueView",
    "StudentCertificateListView",
    "StudentCertificateRetrieveView",
    "CertificatePublicVerifyView",
    "StudentAcademicReportView",
    "EnrollmentReportView",
    "AttendanceReportView",
    "ProgressReportView",
    "CertificateReportView",
    "ClassReportView",
    "SubProgramReportView",
    "ProgramReportView",
]
