# Generated by Django 5.2.15 on 2026-07-16 09:18

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shared', '0002_auditlog_details'),
    ]

    operations = [
        migrations.CreateModel(
            name='BankAccount',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('bank_name', models.CharField(max_length=200)),
                ('account_holder', models.CharField(max_length=200)),
                ('account_number', models.CharField(max_length=100)),
                ('branch', models.CharField(blank=True, default='', max_length=200)),
                ('swift_code', models.CharField(blank=True, default='', max_length=50)),
                ('iban', models.CharField(blank=True, default='', max_length=50)),
                ('is_active', models.BooleanField(default=True)),
                ('notes', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'shared_bank_account',
                'ordering': ['bank_name', 'account_holder'],
            },
        ),
    ]
