# Generated by Django 5.2.15 on 2026-07-21 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shared', '0003_add_bank_account_model'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='bankaccount',
            constraint=models.UniqueConstraint(fields=('bank_name', 'account_number'), name='uq_bank_name_account_number'),
        ),
    ]
